### ISSUE TITLE
при запуске докер контейнера бот выдает ошибку KeyError: 'fsm_mode'

### ISSUE THREAD

**Issue by Integrated0** [MasterGroosha/telegram-casino-bot#6]
пытался запустить докер контейнер через docker-compose up -d
контейнер telegram-casino-redis работает и запускается
контейнер telegram-casino-bot выдает ошибку и перезапускается постоянно
логи прикрепил ниже

@MasterGroosha , помоги пожалуйста пофиксить ошибку
готов поддержать донатом ( телеграм @xxanqr )

2023-02-08 23:50:51 Traceback (most recent call last):
2023-02-08 23:50:51   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-02-08 23:50:51     return _run_code(code, main_globals, None,
2023-02-08 23:50:51   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
2023-02-08 23:50:51     exec(code, run_globals)
2023-02-08 23:50:51   File "/app/bot/__main__.py", line 8, in <module>
2023-02-08 23:50:51     from bot.config_reader import config
2023-02-08 23:50:51   File "/app/bot/config_reader.py", line 28, in <module>
2023-02-08 23:50:51     config = Settings()
2023-02-08 23:50:51   File "pydantic/env_settings.py", line 38, in pydantic.env_settings.BaseSettings.__init__
2023-02-08 23:50:51   File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
2023-02-08 23:50:51   File "pydantic/main.py", line 1038, in pydantic.main.validate_model
2023-02-08 23:50:51   File "pydantic/fields.py", line 850, in pydantic.fields.ModelField.validate
2023-02-08 23:50:51   File "pydantic/fields.py", line 1121, in pydantic.fields.ModelField._apply_validators
2023-02-08 23:50:51   File "pydantic/class_validators.py", line 282, in pydantic.class_validators._generic_validator_cls.lambda4
2023-02-08 23:50:51   File "/app/bot/config_reader.py", line 19, in skip_validating_redis
2023-02-08 23:50:51     if values["fsm_mode"] == "redis" and v is None:
2023-02-08 23:50:51 KeyError: 'fsm_mode'
2023-02-08 23:50:52 Traceback (most recent call last):
2023-02-08 23:50:52   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-02-08 23:50:52     return _run_code(code, main_globals, None,
2023-02-08 23:50:52   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
2023-02-08 23:50:52     exec(code, run_globals)
2023-02-08 23:50:52   File "/app/bot/__main__.py", line 8, in <module>
2023-02-08 23:50:52     from bot.config_reader import config
2023-02-08 23:50:52   File "/app/bot/config_reader.py", line 28, in <module>
2023-02-08 23:50:52     config = Settings()
2023-02-08 23:50:52   File "pydantic/env_settings.py", line 38, in pydantic.env_settings.BaseSettings.__init__
2023-02-08 23:50:52   File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
2023-02-08 23:50:52   File "pydantic/main.py", line 1038, in pydantic.main.validate_model
2023-02-08 23:50:52   File "pydantic/fields.py", line 850, in pydantic.fields.ModelField.validate
2023-02-08 23:50:52   File "pydantic/fields.py", line 1121, in pydantic.fields.ModelField._apply_validators
2023-02-08 23:50:52   File "pydantic/class_validators.py", line 282, in pydantic.class_validators._generic_validator_cls.lambda4
2023-02-08 23:50:52   File "/app/bot/config_reader.py", line 19, in skip_validating_redis
2023-02-08 23:50:52     if values["fsm_mode"] == "redis" and v is None:
2023-02-08 23:50:52 KeyError: 'fsm_mode'
2023-02-08 23:50:53 Traceback (most recent call last):
2023-02-08 23:50:53   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-02-08 23:50:53     return _run_code(code, main_globals, None,
2023-02-08 23:50:53   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
2023-02-08 23:50:53     exec(code, run_globals)
2023-02-08 23:50:53   File "/app/bot/__main__.py", line 8, in <module>
2023-02-08 23:50:53     from bot.config_reader import config
2023-02-08 23:50:53   File "/app/bot/config_reader.py", line 28, in <module>
2023-02-08 23:50:53     config = Settings()
2023-02-08 23:50:53   File "pydantic/env_settings.py", line 38, in pydantic.env_settings.BaseSettings.__init__
2023-02-08 23:50:53   File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
2023-02-08 23:50:53   File "pydantic/main.py", line 1038, in pydantic.main.validate_model
2023-02-08 23:50:53   File "pydantic/fields.py", line 850, in pydantic.fields.ModelField.validate
2023-02-08 23:50:53   File "pydantic/fields.py", line 1121, in pydantic.fields.ModelField._apply_validators
2023-02-08 23:50:53   File "pydantic/class_validators.py", line 282, in pydantic.class_validators._generic_validator_cls.lambda4
2023-02-08 23:50:53   File "/app/bot/config_reader.py", line 19, in skip_validating_redis
2023-02-08 23:50:53     if values["fsm_mode"] == "redis" and v is None:
2023-02-08 23:50:53 KeyError: 'fsm_mode'
2023-02-08 23:50:54 Traceback (most recent call last):
2023-02-08 23:50:54   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-02-08 23:50:54     return _run_code(code, main_globals, None,
2023-02-08 23:50:54   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
2023-02-08 23:50:54     exec(code, run_globals)
2023-02-08 23:50:54   File "/app/bot/__main__.py", line 8, in <module>
2023-02-08 23:50:54     from bot.config_reader import config
2023-02-08 23:50:54   File "/app/bot/config_reader.py", line 28, in <module>
2023-02-08 23:50:54     config = Settings()
2023-02-08 23:50:54   File "pydantic/env_settings.py", line 38, in pydantic.env_settings.BaseSettings.__init__
2023-02-08 23:50:54   File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
2023-02-08 23:50:54   File "pydantic/main.py", line 1038, in pydantic.main.validate_model
2023-02-08 23:50:54   File "pydantic/fields.py", line 850, in pydantic.fields.ModelField.validate
2023-02-08 23:50:54   File "pydantic/fields.py", line 1121, in pydantic.fields.ModelField._apply_validators
2023-02-08 23:50:54   File "pydantic/class_validators.py", line 282, in pydantic.class_validators._generic_validator_cls.lambda4
2023-02-08 23:50:54   File "/app/bot/config_reader.py", line 19, in skip_validating_redis
2023-02-08 23:50:54     if values["fsm_mode"] == "redis" and v is None:
2023-02-08 23:50:54 KeyError: 'fsm_mode'
2023-02-08 23:50:56 Traceback (most recent call last):
2023-02-08 23:50:56   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-02-08 23:50:56     return _run_code(code, main_globals, None,
2023-02-08 23:50:56   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
2023-02-08 23:50:56     exec(code, run_globals)
2023-02-08 23:50:56   File "/app/bot/__main__.py", line 8, in <module>
2023-02-08 23:50:56     from bot.config_reader import config
2023-02-08 23:50:56   File "/app/bot/config_reader.py", line 28, in <module>
2023-02-08 23:50:56     config = Settings()
2023-02-08 23:50:56   File "pydantic/env_settings.py", line 38, in pydantic.env_settings.BaseSettings.__init__
2023-02-08 23:50:56   File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
2023-02-08 23:50:56   File "pydantic/main.py", line 1038, in pydantic.main.validate_model
2023-02-08 23:50:56   File "pydantic/fields.py", line 850, in pydantic.fields.ModelField.validate
2023-02-08 23:50:56   File "pydantic/fields.py", line 1121, in pydantic.fields.ModelField._apply_validators
2023-02-08 23:50:56   File "pydantic/class_validators.py", line 282, in pydantic.class_validators._generic_validator_cls.lambda4
2023-02-08 23:50:56   File "/app/bot/config_reader.py", line 19, in skip_validating_redis
2023-02-08 23:50:56     if values["fsm_mode"] == "redis" and v is None:
2023-02-08 23:50:56 KeyError: 'fsm_mode'
2023-02-08 23:50:59 Traceback (most recent call last):
2023-02-08 23:50:59   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-02-08 23:50:59     return _run_code(code, main_globals, None,
2023-02-08 23:50:59   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
2023-02-08 23:50:59     exec(code, run_globals)
2023-02-08 23:50:59   File "/app/bot/__main__.py", line 8, in <module>
2023-02-08 23:50:59     from bot.config_reader import config
2023-02-08 23:50:59   File "/app/bot/config_reader.py", line 28, in <module>
2023-02-08 23:50:59     config = Settings()
2023-02-08 23:50:59   File "pydantic/env_settings.py", line 38, in pydantic.env_settings.BaseSettings.__init__
2023-02-08 23:50:59   File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
2023-02-08 23:50:59   File "pydantic/main.py", line 1038, in pydantic.main.validate_model
2023-02-08 23:50:59   File "pydantic/fields.py", line 850, in pydantic.fields.ModelField.validate
2023-02-08 23:50:59   File "pydantic/fields.py", line 1121, in pydantic.fields.ModelField._apply_validators
2023-02-08 23:50:59   File "pydantic/class_validators.py", line 282, in pydantic.class_validators._generic_validator_cls.lambda4
2023-02-08 23:50:59   File "/app/bot/config_reader.py", line 19, in skip_validating_redis
2023-02-08 23:50:59     if values["fsm_mode"] == "redis" and v is None:
2023-02-08 23:50:59 KeyError: 'fsm_mode'
2023-02-08 23:51:03 Traceback (most recent call last):
2023-02-08 23:51:03   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-02-08 23:51:03     return _run_code(code, main_globals, None,
2023-02-08 23:51:03   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
2023-02-08 23:51:03     exec(code, run_globals)
2023-02-08 23:51:03   File "/app/bot/__main__.py", line 8, in <module>
2023-02-08 23:51:03     from bot.config_reader import config
2023-02-08 23:51:03   File "/app/bot/config_reader.py", line 28, in <module>
2023-02-08 23:51:03     config = Settings()
2023-02-08 23:51:03   File "pydantic/env_settings.py", line 38, in pydantic.env_settings.BaseSettings.__init__
2023-02-08 23:51:03   File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
2023-02-08 23:51:03   File "pydantic/main.py", line 1038, in pydantic.main.validate_model
2023-02-08 23:51:03   File "pydantic/fields.py", line 850, in pydantic.fields.ModelField.validate
2023-02-08 23:51:03   File "pydantic/fields.py", line 1121, in pydantic.fields.ModelField._apply_validators
2023-02-08 23:51:03   File "pydantic/class_validators.py", line 282, in pydantic.class_validators._generic_validator_cls.lambda4
2023-02-08 23:51:03   File "/app/bot/config_reader.py", line 19, in skip_validating_redis
2023-02-08 23:51:03     if values["fsm_mode"] == "redis" and v is None:
2023-02-08 23:51:03 KeyError: 'fsm_mode'
2023-02-08 23:51:11 Traceback (most recent call last):
2023-02-08 23:51:11   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-02-08 23:51:11     return _run_code(code, main_globals, None,
2023-02-08 23:51:11   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
2023-02-08 23:51:11     exec(code, run_globals)
2023-02-08 23:51:11   File "/app/bot/__main__.py", line 8, in <module>
2023-02-08 23:51:11     from bot.config_reader import config
2023-02-08 23:51:11   File "/app/bot/config_reader.py", line 28, in <module>
2023-02-08 23:51:11     config = Settings()
2023-02-08 23:51:11   File "pydantic/env_settings.py", line 38, in pydantic.env_settings.BaseSettings.__init__
2023-02-08 23:51:11   File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
2023-02-08 23:51:11   File "pydantic/main.py", line 1038, in pydantic.main.validate_model
2023-02-08 23:51:11   File "pydantic/fields.py", line 850, in pydantic.fields.ModelField.validate
2023-02-08 23:51:11   File "pydantic/fields.py", line 1121, in pydantic.fields.ModelField._apply_validators
2023-02-08 23:51:11   File "pydantic/class_validators.py", line 282, in pydantic.class_validators._generic_validator_cls.lambda4
2023-02-08 23:51:11   File "/app/bot/config_reader.py", line 19, in skip_validating_redis
2023-02-08 23:51:11     if values["fsm_mode"] == "redis" and v is None:
2023-02-08 23:51:11 KeyError: 'fsm_mode'
2023-02-08 23:51:24 Traceback (most recent call last):
2023-02-08 23:51:24   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-02-08 23:51:24     return _run_code(code, main_globals, None,
2023-02-08 23:51:24   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
2023-02-08 23:51:24     exec(code, run_globals)
2023-02-08 23:51:24   File "/app/bot/__main__.py", line 8, in <module>
2023-02-08 23:51:24     from bot.config_reader import config
2023-02-08 23:51:24   File "/app/bot/config_reader.py", line 28, in <module>
2023-02-08 23:51:24     config = Settings()
2023-02-08 23:51:24   File "pydantic/env_settings.py", line 38, in pydantic.env_settings.BaseSettings.__init__
2023-02-08 23:51:24   File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
2023-02-08 23:51:24   File "pydantic/main.py", line 1038, in pydantic.main.validate_model
2023-02-08 23:51:24   File "pydantic/fields.py", line 850, in pydantic.fields.ModelField.validate
2023-02-08 23:51:24   File "pydantic/fields.py", line 1121, in pydantic.fields.ModelField._apply_validators
2023-02-08 23:51:24   File "pydantic/class_validators.py", line 282, in pydantic.class_validators._generic_validator_cls.lambda4
2023-02-08 23:51:24   File "/app/bot/config_reader.py", line 19, in skip_validating_redis
2023-02-08 23:51:24     if values["fsm_mode"] == "redis" and v is None:
2023-02-08 23:51:24 KeyError: 'fsm_mode'

**Comment by MasterGroosha** [comment]
Судя по ошибке, в файле конфига нет опции fsm_mode

**Comment by MasterGroosha** [comment]
@Integrated0 считаю, что проблема решена. Если нет, пиши комментарий

**Comment by JoyoUA** [comment]
Да, есть такая проблема:
2023-03-16 14:11:54 telegram-casino-bot-bot-1    | Traceback (most recent call last):
2023-03-16 14:11:54 telegram-casino-bot-bot-1    |   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-03-16 14:11:54 telegram-casino-bot-bot-1    |     return _run_code(code, main_globals, None,
2023-03-16 14:11:54 telegram-casino-bot-bot-1    |   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
2023-03-16 14:11:54 telegram-casino-bot-bot-1    |     exec(code, run_globals)
2023-03-16 14:11:54 telegram-casino-bot-bot-1    |   File "/app/bot/__main__.py", line 8, in <module>
2023-03-16 14:11:54 telegram-casino-bot-bot-1    |     from bot.config_reader import config
2023-03-16 14:11:54 telegram-casino-bot-bot-1    |   File "/app/bot/config_reader.py", line 28, in <module>
2023-03-16 14:11:54 telegram-casino-bot-bot-1    |     config = Settings()
2023-03-16 14:11:54 telegram-casino-bot-bot-1    |   File "pydantic/env_settings.py", line 38, in pydantic.env_settings.BaseSettings.__init__
2023-03-16 14:11:54 telegram-casino-bot-bot-1    |   File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
2023-03-16 14:11:54 telegram-casino-bot-bot-1    |   File "pydantic/main.py", line 1038, in pydantic.main.validate_model
2023-03-16 14:11:54 telegram-casino-bot-bot-1    |   File "pydantic/fields.py", line 850, in pydantic.fields.ModelField.validate
2023-03-16 14:11:54 telegram-casino-bot-bot-1    |   File "pydantic/fields.py", line 1121, in pydantic.fields.ModelField._apply_validators
2023-03-16 14:11:54 telegram-casino-bot-bot-1    |   File "pydantic/class_validators.py", line 282, in pydantic.class_validators._generic_validator_cls.lambda4
2023-03-16 14:11:54 telegram-casino-bot-bot-1    |   File "/app/bot/config_reader.py", line 19, in skip_validating_redis
2023-03-16 14:11:54 telegram-casino-bot-bot-1    |     if values["fsm_mode"] == "redis" and v is None:
2023-03-16 14:11:54 telegram-casino-bot-bot-1    | KeyError: 'fsm_mode'
1970-01-01 03:00:00 telegram-casino-bot-bot-1 exited with code 1

**Comment by MasterGroosha** [comment]
@JoyoUA 

Ну то же самое.
Как выглядит конфиг? Приватные данные (токены) лучше заменить на заглушки

**Comment by JoyoUA** [comment]
.env

bot_token=token

fsm_mode=redis

redis=redis://user:pass@host:port

.yml

version: "3.8"
services:
    bot:
        # Универсальный образ для x86/ARM64
        image: groosha/telegram-casino-bot:latest
        restart: "always"
        stop_signal: SIGINT
        volumes:
            # Путь к .env файлу с настройками
            - "/.env"
        depends_on:
            - redis
    redis:
        image: redis:7
        restart: "always"
        volumes:
            # Путь к каталогу с redis.conf
            - "/redis.conf"
            # Путь к каталогу, где будет лежать дамп базы Redis
            - "/redis_data:/data"
        command: "redis-server /redis.conf"

**Comment by MasterGroosha** [comment]
@JoyoUA 

> Путь к .env файлу с настройками
>  "/.env"

Как-то не похоже не правду. А если попробовать полный вариант? типа такого

`"/home/user/casino-bot-redis/.env:/app/.env"`

**Comment by JoyoUA** [comment]
любой другой введённый путь вызывает ошибку: Error response from daemon: invalid mount config for type "volume": invalid mount path: 'telegram-casino-bot/.env' mount path must be absolute

**Comment by MasterGroosha** [comment]
@JoyoUA ну так да, "must be absolute". У меня в примере и выше в комментарии указан абсолютный путь.
